const resList = [
  {
    id: 1,
    name: "Burger King",
    cuisines: ["Burgers", "American"],
    rating: 3.6,
    deliveryTime: "25–30 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOX2YyS0W1LnrD5eyd-7Q9kvO1JGvE80AXXA&s",
    area: "Thane West",
    price: "₹150 for one",
    offer: "Items at ₹19",
  },
  {
    id: 2,
    name: "KFC",
    cuisines: ["Fried Chicken", "Fast Food"],
    rating: 4.2,
    deliveryTime: "20–25 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZF4y3jIjSmtajWX_3XLGyGtxpysq02J4dQ&s",
    area: "Mulund",
    price: "₹200 for one",
    offer: "20% OFF",
  },
  {
    id: 3,
    name: "McDonald's",
    cuisines: ["Burgers", "Cafe"],
    rating: 4.4,
    deliveryTime: "22–28 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiJ5cMOZUqLmUP_xykwtnWmPQFo6-0gYns6A&s",
    area: "Bandra West",
    price: "₹180 for one",
    offer: "Free Fries",
  },
  {
    id: 4,
    name: "Domino's Pizza",
    cuisines: ["Pizza", "Fast Food"],
    rating: 3.9,
    deliveryTime: "25–35 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMZQOMZrKrNeoWiVHpzb4FQGMyiyvAxDrKpA&s",
    area: "Dadar",
    price: "₹250 for one",
    offer: "50% OFF",
  },
  {
    id: 5,
    name: "Subway",
    cuisines: ["Healthy", "Sandwiches"],
    rating: 3.8,
    deliveryTime: "15–20 mins",
    imageId: "https://eatingrules.com/wp-content/uploads/2010/05/healthy-options-at-subway.jpg",
    area: "Ghatkopar",
    price: "₹190 for one",
    offer: "Buy 1 Get 1",
  },
  {
    id: 6,
    name: "Pizza Hut",
    cuisines: ["Pizza", "Italian"],
    rating: 4.1,
    deliveryTime: "20–30 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLCur9jdMtWeTLs-Do_FM8NAY6pZ96vb0esA&s",
    area: "Thane East",
    price: "₹230 for one",
    offer: "20% OFF",
  },
  {
    id: 7,
    name: "Barbeque Nation",
    cuisines: ["North Indian", "BBQ"],
    rating: 3.5,
    deliveryTime: "30–40 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMZQOMZrKrNeoWiVHpzb4FQGMyiyvAxDrKpA&s",
    area: "Andheri East",
    price: "₹500 for one",
    offer: "Buffet Deals",
  },
  {
    id: 8,
    name: "Biryani By Kilo",
    cuisines: ["Biryani", "Mughlai"],
    rating: 4.3,
    deliveryTime: "35–45 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZF4y3jIjSmtajWX_3XLGyGtxpysq02J4dQ&s",
    area: "Kurla",
    price: "₹350 for one",
    offer: "Flat ₹100 OFF",
  },
   {
    id: 9,
    name: "Burger King",
    cuisines: ["Burgers", "American"],
    rating: 3.8,
    deliveryTime: "25–30 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOX2YyS0W1LnrD5eyd-7Q9kvO1JGvE80AXXA&s",
    area: "Thane West",
    price: "₹150 for one",
    offer: "Items at ₹19",
  },
  {
    id: 10,
    name: "KFC",
    cuisines: ["Fried Chicken", "Fast Food"],
    rating: 4.2,
    deliveryTime: "20–25 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZF4y3jIjSmtajWX_3XLGyGtxpysq02J4dQ&s",
    area: "Mulund",
    price: "₹200 for one",
    offer: "20% OFF",
  },
  {
    id: 11,
    name: "McDonald's",
    cuisines: ["Burgers", "Cafe"],
    rating: 4.4,
    deliveryTime: "22–28 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiJ5cMOZUqLmUP_xykwtnWmPQFo6-0gYns6A&s",
    area: "Bandra West",
    price: "₹180 for one",
    offer: "Free Fries",
  },
  {
    id: 12,
    name: "Domino's Pizza",
    cuisines: ["Pizza", "Fast Food"],
    rating: 4.1,
    deliveryTime: "25–35 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMZQOMZrKrNeoWiVHpzb4FQGMyiyvAxDrKpA&s",
    area: "Dadar",
    price: "₹250 for one",
    offer: "50% OFF",
  },
  {
    id: 13,
    name: "Subway",
    cuisines: ["Healthy", "Sandwiches"],
    rating: 4.0,
    deliveryTime: "15–20 mins",
    imageId: "https://eatingrules.com/wp-content/uploads/2010/05/healthy-options-at-subway.jpg",
    area: "Ghatkopar",
    price: "₹190 for one",
    offer: "Buy 1 Get 1",
  },
  {
    id: 14,
    name: "Pizza Hut",
    cuisines: ["Pizza", "Italian"],
    rating: 4.1,
    deliveryTime: "20–30 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLCur9jdMtWeTLs-Do_FM8NAY6pZ96vb0esA&s",
    area: "Thane East",
    price: "₹230 for one",
    offer: "20% OFF",
  },
  {
    id: 15,
    name: "Barbeque Nation",
    cuisines: ["North Indian", "BBQ"],
    rating: 4.5,
    deliveryTime: "30–40 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMZQOMZrKrNeoWiVHpzb4FQGMyiyvAxDrKpA&s",
    area: "Andheri East",
    price: "₹500 for one",
    offer: "Buffet Deals",
  },
  {
    id: 16,
    name: "Biryani By Kilo",
    cuisines: ["Biryani", "Mughlai"],
    rating: 4.3,
    deliveryTime: "35–45 mins",
    imageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZF4y3jIjSmtajWX_3XLGyGtxpysq02J4dQ&s",
    area: "Kurla",
    price: "₹350 for one",
    offer: "Flat ₹100 OFF",
  },
];

export default resList